### ISSUE TITLE
[OSWeb] Implement CloudFront header forwarding and caching

### ISSUE THREAD

**Issue by BruceP99166** [openstax/bit#136]
# Description
Enumerate the client headers that the backend servers use and which of those change the response from backend servers, so that CloudFront will cache out content effectively.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.cj10fzg4ref4

For Unified Reading Experience

# Problem Description
In order for CloudFront to cache content for us, we have to enumerate which headers we want it to forward to our origins.  For OSWeb, list which headers need to be forwarded to the backend servers by CloudFront and of those say which change the provided response.

# Notes
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html
- Timing: No Later Than Jan 2019
- Blocks: Nothing

# Acceptance Criteria
- Unified team gets a list of headers marked with which impact response content

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: 
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.
