### ISSUE TITLE
KD 2019 Spring re-engage campaign

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#176]
# Description
We want to leverage the power of personalization to encourage action–this campaign will be designed to gamify the OpenStax adoption process by asking them to meet each milestone on the OpenStax journey. 

Current design: https://invis.io/2EQEKE74SA3

# Acceptance Criteria
There is a page on OpenStax.org that can be access through an email link (will not be included in the menu nav for now). 

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.
