### ISSUE TITLE
[OSWeb] BE: Add admin links that trigger 5xx errors

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#222]
### Description
Give admin a way to trigger 5xx errors so that we can see what happens.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.2zbp7sequkbk

For Unified Reading Experience.
### Checklist for Done
- 2-DDD
  - [ ] Description is complete 
  - [ ] Acceptance Criteria is complete
  - [ ] Test criterias are defined
  - [ ] Estimate is updated
  - [ ] If the issue is a story, then Epic is selected
  - [ ] If the issue is included in the quarterly plan, then Milestone is selected
  - [ ] If the issue is included in a product phase, then Release is selected
- 2B-UX DESIGN
  - [ ] The UX design is complete and the design files are attached to the issue
  - [ ] The UX design is approved by the Product Manager
  - [ ] The test plan is drafted.
- 3-CODE
  - [ ] The code change meets the acceptance criteria (for a story or change request), or fixes the identified defect (for a bug)
  - [ ] Affected areas in the code are identified
  - [ ] The code change is merged to master (dev review done, test suite passed, code coverage maintained)
- 3A-NOT CODE
  - [ ] The work is completed and meets the acceptance criteria for the issue
- 4A-UX REVIEW
  - [ ] The implemented feature is accepted by the UX Designer and the Product Manager
  - [ ] The test plan is finalized
- 5A-FUNCT VER
  - [ ] All tests in test plan passed
- 5C-REGRESSION
  - [ ] Affected areas that were identified are passed

- **QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

- **Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by Malar-Natarajan** [comment]
Verified in QA
