### ISSUE TITLE
[OSWeb] BE: Alias all API endpoints under an /apps/cms/api prefix

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#228]
### Description
On the OS CMS, alias all API endpoints to be accessible under an `/apps/cms/api/` prefix so that the CMS endpoints follow the same pattern as other APIs under the Unified CloudFront distribution and so that we can invalidate only CMS API responses cached in CloudFront.

For the Unified Reading Experience
### Checklist for Done
- 2-DDD
  - [ ] Description is complete 
  - [ ] Acceptance Criteria is complete
  - [ ] Test criterias are defined
  - [ ] Estimate is updated
  - [ ] If the issue is a story, then Epic is selected
  - [ ] If the issue is included in the quarterly plan, then Milestone is selected
  - [ ] If the issue is included in a product phase, then Release is selected
- 2B-UX DESIGN
  - [ ] The UX design is complete and the design files are attached to the issue
  - [ ] The UX design is approved by the Product Manager
  - [ ] The test plan is drafted.
- 3-CODE
  - [ ] The code change meets the acceptance criteria (for a story or change request), or fixes the identified defect (for a bug)
  - [ ] Affected areas in the code are identified
  - [ ] The code change is merged to master (dev review done, test suite passed, code coverage maintained)
- 3A-NOT CODE
  - [ ] The work is completed and meets the acceptance criteria for the issue
- 4A-UX REVIEW
  - [ ] The implemented feature is accepted by the UX Designer and the Product Manager
  - [ ] The test plan is finalized
- 5A-FUNCT VER
  - [ ] All tests in test plan passed
- 5C-REGRESSION
  - [ ] Affected areas that were identified are passed

- **QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

- **Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by mwharrison** [comment]
@jpslav are you only expecting the API requests to change their URL structure - or other pages as well, such as `/admin`, `/auth`, etc.?
