### ISSUE TITLE
Lightning Rollout - Exec team

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#235]
### Description
The Salesforce team is rolling out the Lightning experience to our internal users. We are meeting with each team to 1) personalize their view in Salesforce, 2) understand their needs to help us plan for the future, and 3) create documentation of those things for future plans and/or training. 
### Checklist for Done
- [ ] Interview team member
- [ ] Create documentation for training 
- [ ] Create custom page layout for team
- [ ] Train team member on new functionality
