### ISSUE TITLE
KD Investigate CRM maintenance options

### ISSUE THREAD

**Issue by laurenloh** [openstax/bit#237]
# Description
We are investigating ways to improve spot-checking of our adoption data. We currently contract with ABS to do this work, but there are companies that can help us automate and improve the process.

Our adoption data is submitted voluntarily, which means we don’t know about many adoptions, but this is the best way to measure our impact and secure more funding. We need to find a reliable way to learn about new adoptions and update old ones. This should help us do that.

# Acceptance Criteria
- We have picked a company to work with
- The contract is signed
# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.
