### ISSUE TITLE
Install Crazy Egg tracking script on openstax.org

### ISSUE THREAD

**Issue by allisonhowell** [openstax/bit#286]
# Description
Crazy Egg uses heat maps to give insight into user behavior on websites. Directions are in the comments of the card. 

Paste the JavaScript tag into the <head> of your website.
<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0013/0704.js" async="async"></script>
If you need help, don't hesitate to email support@crazyegg.com or check out our step-by-step installation guides for WordPress, Shopify, Squarespace, Drupal, Joomla!, and Magento. 

# Acceptance Criteria
- The JavaScript tag is added to openstax.org
- Optidge and the marcom team can view the heat maps for select pages on openstax.org 

# Acceptance Tests
This will be tested by Allison and the marcom team. 

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [x] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
Paste the JavaScript tag into the <head> of your website.
<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0013/0704.js" async="async"></script>
If you need help, don't hesitate to email support@crazyegg.com or check out our step-by-step installation guides for WordPress, Shopify, Squarespace, Drupal, Joomla!, and Magento.

**Comment by RoyEJohnson** [comment]
@allisonhowell Can you test to see that this is working on dev, or does it need to go into Production before you can tell?

**Comment by allisonhowell** [comment]
@RoyEJohnson I can't tell because I don't have the Crazy Egg account - it's held by our consultant. I think this will have to move along without testing.
